---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: vars-store

params:
  VARS_STORE_FILE: # path to vars store file inside the vars-store resource

run:
  path: backup-and-restore-ci/tasks/create-external-cf-databases/task.sh
