---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: homebrew-tap
- name: bbr-release

outputs:
- name: updated-homebrew-tap

run:
  path: backup-and-restore-ci/tasks/bbr-update-homebrew-formula/task.sh
