---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.19.0

inputs:
- name: backup-and-restore-ci
- name: terraform
- name: bbl-state

outputs:
- name: k-drats-config

params:
  BBL_STATE_DIR:  # Path to bbl state inside bbl-state resource
  TIMEOUT_IN_MINUTES: 30
  CLUSTER_NAME: kubo
  KUBO_USERNAME: admin
  BOSH_DIRECTOR_NAME:  # Top level of path to credhub secrets
  BOSH_DEPLOYMENT:  # Second level of path to credhub secrets

run:
  path: backup-and-restore-ci/tasks/extract-k-drats-config/task.sh
