---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: bosh-state
- name: bosh-deployment
- name: terraform-state
- name: opsfiles

outputs:
- name: bosh-state-updated

params:
  DIRECTOR_NAME:
  ENVIRONMENT_NAME:
  JUMPBOX_ENVIRONMENT_NAME:
  GCP_SERVICE_ACCOUNT_KEY:
  BOSH_OPERATION: create-env # Set bosh command to run, e.g. create-env or delete-env

run:
  path: backup-and-restore-ci/tasks/bosh-operation/task.sh
