---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: terraform-state

outputs:
- name: meta-with-updated-terraform

params:
  TERRAFORM_STATE_DIR: terraform-state
  TERRFORM_STATE_PREPARE_CMD:  # Optional command to run before using terrform-state repository
  OUTPUT_TERRAFORM_STATE_DIR: meta-with-updated-terraform
  ENVIRONMENT_NAME:
  GIT_USER_NAME:
  GIT_USER_EMAIL:

run:
  path: backup-and-restore-ci/tasks/terraform-apply/task.sh
