---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: bosh-state
- name: bosh-deployment

outputs:
- name: meta-with-updated-bosh-state

params:
  BOSH_STATE_DIR: bosh-state
  BOSH_STATE_PREPARE_CMD:  # Optional command to run before using bosh-state repository
  BOSH_STATE_OUTPUT_DIR: meta-with-updated-bosh-state
  OPS_FILES:
  DIRECTOR_NAME:
  ENVIRONMENT_NAME:
  PROJECT_ID:
  ZONE:
  TAGS:
  IP:
  NETWORK:
  SUBNET:

run:
  path: backup-and-restore-ci/tasks/bosh-create-env/task.sh
