---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: bosh-backup-and-restore-meta
- name: bosh-deployment

params:
  BOSH_STATE_DIR:
  TEAM_GPG_KEY:
  OPS_FILES:
  DIRECTOR_NAME:
  BOSH_STATE_DIR:
  PROJECT_ID:
  ZONE:
  TAG:
  IP:
  NETWORK:
  SUBNET:

outputs:
- name: meta-with-updated-bosh-state

run:
  path: backup-and-restore-ci/tasks/generate-release-metadata/task