---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: bosh-state
- name: bosh-deployment
- name: terraform-state

outputs:
- name: bosh-state-updated

params:
  BOSH_STATE_DIR: bosh-state
  TERRAFORM_STATE_DIR: terraform-state
  BOSH_STATE_PREPARE_CMD:  # Optional command to run before using bosh-state repository
  BOSH_STATE_OUTPUT_DIR: bosh-state-updated
  OPS_FILES:
  DIRECTOR_NAME:
  ENVIRONMENT_NAME:

run:
  path: backup-and-restore-ci/tasks/bosh-create-env/task.sh
