---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: pcfplatformrecovery/backup-and-restore

inputs:
- name: backup-and-restore-ci
- name: terraform

params:
  ADDRESS:


run:
  path: backup-and-restore-ci/tasks/check-dns-resolves/task.sh
