---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: bosh-backup-and-restore-meta

outputs:
- name: bosh-backup-and-restore-meta

params:
  RDS_CA_BUNDLE_URL: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
  RDS_CA_BUNDLE_PATH: ci/backup-and-restore-sdk-release/certs/rds-combined-ca-bundle.pem
  GIT_COMMIT_EMAIL:
  GIT_COMMIT_USERNAME:


run:
  path: backup-and-restore-ci/tasks/get-latest-rds-ca-bundle/task.sh
