---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v3.15.0

inputs:
- name: backup-and-restore-ci
- name: bbl-state

params:
  BBL_STATE_DIR:
  ERRAND_NAMES:

run:
  path: backup-and-restore-ci/tasks/run-errands/task.sh
