---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfplatformrecovery/backup-and-restore-minimal}

inputs:
- name: ci
- name: env-pool
- name: bbr-s3-config-validator-test-artifacts

run:
  path: ci/tasks/bbr-s3-config-validator-validate-aws-s3-config/task.sh
