#!/usr/bin/env bash

set -eux -o pipefail

if [ -e release/*.tar ]; then
    cp release/*.tar release-with-metadata/
    export RELEASE_TAR=$(ls release-with-metadata/*.tar)
fi

if [ -e release/*.tgz ]; then
    cp release/*.tgz release-with-metadata/
    export RELEASE_TAR=$(ls release-with-metadata/*.tgz)
fi

export VERSION=$(cat version-folder/${VERSION_PATH})
erb -T- template-folder/${TEMPLATE_PATH} > release-with-metadata/release.yml