#!/usr/bin/env bash

set -eux -o pipefail

cp release/{*.tar,*.tgz} release-with-metadata/
export RELEASE_TAR=$(ls release-with-metadata/ | head -1)
export VERSION=$(cat version-folder/${VERSION_PATH})
erb -T- template-folder/${TEMPLATE_PATH} > release-with-metadata/release.yml