---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: cloud-config
- name: terraform-state
- name: bosh-vars-store
- name: backup-and-restore-ci
- name: opsfiles

params:
  CLOUD_CONFIG_PATH:
  BOSH_VARS_STORE_PATH:  # Path to bosh director vars-store YAML file
  BOSH_CLIENT:
  JUMPBOX_VARS_STORE_PATH:

run:
  path: backup-and-restore-ci/tasks/update-b-drats-cloud-config/task.sh
