---
toolsmiths_api_worker: &toolsmiths_api_worker vsphere-platform-recovery
toolsmiths_pool_worker: &toolsmiths_pool_worker toolsmiths-pool

groups:
- name: BUILD
  jobs:
  - upload-systest-releases
  - unit
  - system
  - system-uaa
  - system-director
  - build-rc
  - install-optional-components-on-pas
  - run-p-drats-on-pas
  - transfer-bbr-binary-to-jumpbox
- name: SHIPIT
  jobs:
  - build-final
  - publish-release

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

- name: git
  type: docker-image
  source:
    repository: concourse/git-resource
    tag: latest

resources:
- name: pcf-2-1-pool
  type: pcf-pool
  source:
    api_token: ((toolsmiths-api-token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: us_2_1
  tags:
  - *toolsmiths_api_worker

- name: bosh-backup-and-restore
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bosh-backup-and-restore.git
    private_key: ((git-private-key))
    branch: master
    disable_git_lfs: true
- name: bosh-backup-and-restore-meta
  type: git
  source:
    uri: git@github.com:pivotal-cf/bosh-backup-and-restore-meta.git
    private_key: ((git-private-key))
    git_crypt_key: ((git-crypt-key))
    branch: master
- name: release-trigger
  type: git
  source:
    uri: git@github.com:pivotal-cf/bosh-backup-and-restore-meta.git
    private_key: ((git-private-key))
    git_crypt_key: ((git-crypt-key))
    branch: master
    paths:
    - bbr-current-release/version
- name: backup-and-restore-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master
- name: bbr-pivnet
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-bosh-backup-and-restore
    access_key_id: ((pivnet-aws-access-key-id))
    secret_access_key: ((pivnet-aws-secret-access-key))
- name: rc
  type: s3
  source:
    bucket: bosh-backup-and-restore-builds
    region_name: eu-west-1
    regexp: bbr-(.*)\.tar
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
- name: release
  type: s3
  source:
    bucket: bosh-backup-and-restore-final-builds
    region_name: eu-west-1
    regexp: bbr-(.*)\.tar
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
- name: version
  type: semver
  source:
    bucket: bosh-backup-and-restore-builds
    region_name: eu-west-1
    key: current-version
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
- name: bbr-release
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github-access-token))
    drafts: true
- name: bbr-systest-releases
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/bosh-backup-and-restore-test-releases.git
    private_key: ((git-private-key))
    branch: master
    paths: [redis-test-release/**, lock-ordering-release/**]
- name: pivotal-disaster-recovery-acceptance-tests
  type: git
  source:
    uri: git@github.com:pivotal-cf/pivotal-disaster-recovery-acceptance-tests.git
    private_key: ((git-private-key))
    branch: master


jobs:
- name: upload-systest-releases
  serial: true
  plan:
  - get: bosh-backup-and-restore
    trigger: true
    params:
      submodules: none
      disable_git_lfs: true
  - get: bbr-systest-releases
    trigger: true
  - get: bosh-backup-and-restore-meta
  - task: upload-redis-test-release
    file: bosh-backup-and-restore/ci/tasks/upload-systest-release.yml
    params:
      BOSH_HOST: lite-bosh.backup-and-restore.cf-app.com
      BOSH_CLIENT: ((garden-bosh-director-username))
      BOSH_CLIENT_SECRET: ((garden-bosh-director-password))
      BOSH_UAA_HOST: lite-bosh-uaa.backup-and-restore.cf-app.com
      BOSH_UAA_CLIENT_SECRET: ((uaa-director-password))
      RELEASE_NAME: redis-test-release
  - task: upload-lock-ordering-release
    file: bosh-backup-and-restore/ci/tasks/upload-systest-release.yml
    params:
      BOSH_HOST: lite-bosh.backup-and-restore.cf-app.com
      BOSH_CLIENT: ((garden-bosh-director-username))
      BOSH_CLIENT_SECRET: ((garden-bosh-director-password))
      BOSH_UAA_HOST: lite-bosh-uaa.backup-and-restore.cf-app.com
      BOSH_UAA_CLIENT_SECRET: ((uaa-director-password))
      RELEASE_NAME: lock-ordering-release
- name: unit
  serial: true
  plan:
  - get: bosh-backup-and-restore
    trigger: true
    params:
      submodules: none
      disable_git_lfs: true
  - task: unit
    file: bosh-backup-and-restore/ci/tasks/unit.yml
    privileged: true
    params:
      DOCKER_HOST: "tcp://10.0.3.12:4243"
      GITHUB_SSH_KEY: ((github-ssh-key))
- name: system
  serial: true
  plan:
  - get: bosh-backup-and-restore
    passed: [unit, upload-systest-releases]
    trigger: true
  - get: bosh-backup-and-restore-meta
  - task: system
    file: bosh-backup-and-restore/ci/tasks/system.yml
    params:
      BOSH_HOST: lite-bosh.backup-and-restore.cf-app.com
      BOSH_CLIENT_SECRET: ((director-password))
- name: system-uaa
  serial: true
  plan:
  - get: bosh-backup-and-restore
    passed: [unit, upload-systest-releases]
    trigger: true
  - get: bosh-backup-and-restore-meta
  - task: system
    file: bosh-backup-and-restore/ci/tasks/system.yml
    params:
      BOSH_GATEWAY_USER: jumpbox
      BOSH_GATEWAY_KEY: bosh-backup-and-restore-meta/garden-bosh-uaa/bosh.pem
      BOSH_HOST: lite-bosh-uaa.backup-and-restore.cf-app.com
      BOSH_CLIENT_SECRET: ((uaa-director-password))
- name: system-director
  serial: true
  plan:
  - get: bosh-backup-and-restore
    passed: [unit, upload-systest-releases]
    trigger: true
  - get: bosh-backup-and-restore-meta
  - task: system-director
    file: bosh-backup-and-restore/ci/tasks/system-director.yml
    params:
      BOSH_HOST: genesis-bosh.backup-and-restore.cf-app.com
      BOSH_CLIENT_SECRET: ((genesis-bosh-director-password))
      HOST_TO_BACKUP: 10.0.0.7
- name: build-rc
  serial_groups: [version]
  plan:
  - get: bosh-backup-and-restore
    passed: [system, system-uaa, system-director]
    trigger: true
    params:
      submodules: none
      disable_git_lfs: true
  - get: version
    params: {pre: rc}
  - get: bosh-backup-and-restore-meta
  - task: build
    file: bosh-backup-and-restore/ci/tasks/build.yml
  - put: rc
    params: {file: bbr-build/bbr-*}
  - put: version
    params: {file: version/number}

- name: install-optional-components-on-pas
  serial: true
  plan:
  - aggregate:
    - get: pivotal-disaster-recovery-acceptance-tests
    - get: bosh-backup-and-restore
      passed: [build-rc]
      trigger: true
    - get: rc
      passed: [build-rc]
    - put: env-pool
      resource: pcf-2-1-pool
      params:
        action: claim
      tags:
      - *toolsmiths_api_worker
  - task: enable-internal-blobstore
    file: pivotal-disaster-recovery-acceptance-tests/ci/enable-internal-blobstore-pas/pool-task.yml
  - task: enable-optional-components
    file: pivotal-disaster-recovery-acceptance-tests/ci/enable-optional-components-pas/pool-task.yml
    privileged: true
    params:
      OPS_MAN_VERSION: "2.1"

- name: run-p-drats-on-pas
  serial: true
  plan:
  - get: pivotal-disaster-recovery-acceptance-tests
  - get: bosh-backup-and-restore
    passed: [install-optional-components-on-pas]
  - get: rc
    passed: [install-optional-components-on-pas]
    trigger: true
  - get: env-pool
    resource: pcf-2-1-pool
    passed: [install-optional-components-on-pas]
    tags:
    - *toolsmiths_api_worker
  - task: acceptance-tests
    tags:
    - *toolsmiths_pool_worker
    privileged: true
    file: pivotal-disaster-recovery-acceptance-tests/ci/p-drats-ops-manager/pool-task.yml
    input_mapping:
      bbr-binary-release: rc
    params:
      DEFAULT_TIMEOUT_MINS: 30
  - put: pcf-2-1-pool
    params:
      action: unclaim
      env_file: env-pool/metadata
    tags:
    - *toolsmiths_api_worker

- name: transfer-bbr-binary-to-jumpbox
  serial_groups: [version]
  plan:
    - get: bosh-backup-and-restore
      passed: [run-p-drats-on-pas]
      params:
        submodules: none
        disable_git_lfs: true
    - get: bosh-backup-and-restore-meta
    - get: rc
      passed: [run-p-drats-on-pas]
      trigger: true
    - task: transfer-bbr-binary-to-jumpbox
      file: bosh-backup-and-restore/ci/tasks/transfer-bbr-binary-to-jumpbox.yml
      params:
        BOSH_CLIENT_SECRET: ((genesis-bosh-director-password))
        BOSH_CLIENT: ((genesis-bosh-director-username))
        BOSH_TARGET: https://genesis-bosh.backup-and-restore.cf-app.com
- name: build-final
  serial_groups: [version]
  plan:
  - get: bosh-backup-and-restore-meta
    resource: release-trigger
    trigger: true
  - get: bosh-backup-and-restore
    passed: [run-p-drats-on-pas]
    params:
      submodules: none
      disable_git_lfs: true
  - task: get-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: cloudfoundrylondon/backup-and-restore}
      inputs:
      - name: bosh-backup-and-restore-meta
      outputs:
      - name: bbr-version
      run:
        path: /bin/bash
        args:
        - -c
        - |-
          set -eux
          cat bosh-backup-and-restore-meta/bbr-current-release/version > bbr-version/number
  - task: build
    file: bosh-backup-and-restore/ci/tasks/build.yml
    input_mapping: {version: bbr-version}
  - put: release
    params: {file: bbr-build/bbr-*}
  - put: version
    params: {file: bbr-version/number}
- name: publish-release
  serial: true
  plan:
  - aggregate:
    - get: bosh-backup-and-restore-meta
      resource: release-trigger
      passed: [build-final]
    - get: bosh-backup-and-restore
      passed: [build-final]
      params:
        submodules: none
        disable_git_lfs: true
    - get: release
      passed: [build-final]
      trigger: true
    - get: backup-and-restore-ci
  - task: generate-release-metadata
    file: backup-and-restore-ci/tasks/generate-release-metadata/task.yml
    input_mapping:
      release: release
      version-folder: bosh-backup-and-restore-meta
      template-folder: bosh-backup-and-restore-meta
    params:
      TEMPLATE_PATH: templates/release.yml.erb
      VERSION_PATH: bbr-current-release/version
  - task: generate-release-notes
    file: backup-and-restore-ci/tasks/generate-release-notes/task.yml
    input_mapping:
      repo: bosh-backup-and-restore
      template-folder: bosh-backup-and-restore-meta
    params:
      TEMPLATE_PATH: templates/release-notes.md.erb
  - put: bbr-pivnet
    params:
      metadata_file: release-with-metadata/release.yml
      s3_filepath_prefix: product-files/bosh-backup-restore
      file_glob: release-with-metadata/*.tar
  - put: bbr-release
    params:
      name: bosh-backup-and-restore-meta/bbr-current-release/version
      tag: bosh-backup-and-restore-meta/bbr-current-release/version
      tag_prefix: v
      body: release-notes/release-notes.md
      commitish: bosh-backup-and-restore/.git/refs/heads/master
      globs:
      - release-with-metadata/*.tar
