---
toolsmiths_api_worker: &toolsmiths_api_worker vsphere-platform-recovery
toolsmiths_pool_worker: &toolsmiths_pool_worker toolsmiths-pool

maru-bosh-env: &maru-bosh-env
  BOSH_ENVIRONMENT: "((maru-bosh-director-url))"
  BOSH_CLIENT: "((maru-bosh-director-username))"
  BOSH_CLIENT_SECRET: "((maru-bosh-director-password))"
  BOSH_CA_CERT: "((maru-bosh-director-ca-cert))"
  BOSH_GW_HOST: "((maru-jumpbox-url))"
  BOSH_GW_USER: jumpbox
  BOSH_GW_PRIVATE_KEY: "((maru-jumpbox-ssh-key))"
  USE_BOSH_ALL_PROXY: true

lite-bosh-env: &lite-bosh-env
  BOSH_ENVIRONMENT: lite-bosh.backup-and-restore.cf-app.com
  BOSH_CLIENT: ((garden-bosh-director-username))
  BOSH_CLIENT_SECRET: ((garden-bosh-director-password))
  BOSH_CA_CERT_PATH: bosh-backup-and-restore-meta/certs/lite-bosh.backup-and-restore.cf-app.com.crt

lite-bosh-uaa-env: &lite-bosh-uaa-env
  BOSH_ENVIRONMENT: lite-bosh-uaa.backup-and-restore.cf-app.com
  BOSH_CLIENT: ((uaa-director-username))
  BOSH_CLIENT_SECRET: ((uaa-director-password))
  BOSH_GW_USER: jumpbox
  BOSH_GW_PRIVATE_KEY: bosh-backup-and-restore-meta/garden-bosh-uaa/bosh.pem
  BOSH_CA_CERT_PATH: bosh-backup-and-restore-meta/certs/lite-bosh-uaa.backup-and-restore.cf-app.com.crt

groups:
- name: BUILD
  jobs:
  - upload-systest-releases
  - unit
  - create-test-releases
  - deploy-windows-vm
  - deploy-bosh-directors
  - system
  - system-uaa
  - system-director
  - build-rc
  - install-optional-components-on-pas
  - run-p-drats-on-pas
  - transfer-bbr-binary-to-jumpbox
- name: SHIPIT
  jobs:
  - build-final
  - publish-release

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

- name: git
  type: docker-image
  source:
    repository: concourse/git-resource
    tag: latest

resources:
- name: bosh-backup-and-restore-test-releases
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/bosh-backup-and-restore-test-releases.git
    private_key: {{git-private-key}}
    branch: master
    paths:
    - test-bosh-backup-and-restore-release
- name: dummy-bbr-script-release-bucket
  type: s3
  source:
    bucket: bosh-backup-and-restore-test-releases
    region_name: eu-west-1
    regexp: test-bosh-backup-and-restore-release-(.*).tgz
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
- name: test-release-version
  type: semver
  source:
    bucket: bosh-backup-and-restore-test-releases
    region_name: eu-west-1
    key: current-dev-version
    initial_version: 0.0.0
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: pcf-2-1-pool
  type: pcf-pool
  source:
    api_token: ((toolsmiths-api-token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: us_2_1
  tags:
  - *toolsmiths_api_worker

- name: bosh-backup-and-restore
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bosh-backup-and-restore.git
    private_key: ((git-private-key))
    branch: master
    disable_git_lfs: true
- name: bosh-backup-and-restore-meta
  type: git
  source:
    uri: git@github.com:pivotal-cf/bosh-backup-and-restore-meta.git
    private_key: ((git-private-key))
    git_crypt_key: ((git-crypt-key))
    branch: master
- name: release-trigger
  type: git
  source:
    uri: git@github.com:pivotal-cf/bosh-backup-and-restore-meta.git
    private_key: ((git-private-key))
    git_crypt_key: ((git-crypt-key))
    branch: master
    paths:
    - bbr-current-release/version
- name: backup-and-restore-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master
- name: bbr-pivnet
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-bosh-backup-and-restore
    access_key_id: ((pivnet-aws-access-key-id))
    secret_access_key: ((pivnet-aws-secret-access-key))
- name: rc
  type: s3
  source:
    bucket: bosh-backup-and-restore-builds
    region_name: eu-west-1
    regexp: bbr-(.*)\.tar
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
- name: release
  type: s3
  source:
    bucket: bosh-backup-and-restore-final-builds
    region_name: eu-west-1
    regexp: bbr-(.*)\.tar
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
- name: version
  type: semver
  source:
    bucket: bosh-backup-and-restore-builds
    region_name: eu-west-1
    key: current-version
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
- name: bbr-release
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github-access-token))
    drafts: true
- name: bbr-systest-releases
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/bosh-backup-and-restore-test-releases.git
    private_key: ((git-private-key))
    branch: master
    paths: [redis-test-release/**, lock-ordering-release/**]
- name: pivotal-disaster-recovery-acceptance-tests
  type: git
  source:
    uri: git@github.com:pivotal-cf/pivotal-disaster-recovery-acceptance-tests.git
    private_key: ((git-private-key))
    branch: master
- name: windows-vm-deployment
  type: bosh-deployment
  source:
    deployment: redis-windows-ci
    target: "((maru-bosh-director-url))"
    client: "((maru-bosh-director-username))"
    client_secret: "((maru-bosh-director-password))"
    ca_cert: "((maru-bosh-director-ca-cert))"
    jumpbox_url: "((maru-jumpbox-url))"
    jumpbox_ssh_key: "((maru-jumpbox-ssh-key))"
- name: jumpbox-windows-deployment
  type: bosh-deployment
  source:
    deployment: jumpbox-windows-ci
    target: "((maru-bosh-director-url))"
    client: "((maru-bosh-director-username))"
    client_secret: "((maru-bosh-director-password))"
    ca_cert: "((maru-bosh-director-ca-cert))"
    jumpbox_url: "((maru-jumpbox-url))"
    jumpbox_ssh_key: "((maru-jumpbox-ssh-key))"
- name: windows-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-windows2016-go_agent
- name: ubuntu-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

jobs:
- name: create-test-releases
  plan:
  - aggregate:
    - get: bosh-backup-and-restore-test-releases
      trigger: true
    - get: test-release-version
      params: {pre: "dev"}
    - get: dummy-bbr-script-release-bucket
  - task: create-release
    input_mapping:
      version: test-release-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: cloudfoundrylondon/backup-and-restore}
      inputs:
        - name: bosh-backup-and-restore-test-releases
        - name: version
      outputs:
        - name: bbr-test-release-build
      run:
        path: bash
        args:
        - -uc
        - |
          set -ex
          export VERSION=$(cat version/number)
          pushd bosh-backup-and-restore-test-releases/test-bosh-backup-and-restore-release
            bosh-cli create-release \
              --version=$VERSION \
              --tarball=../../bbr-test-release-build/test-bosh-backup-and-restore-release-$VERSION.tgz \
              --force
          popd
  - put: test-release-version
    params: {file: test-release-version/number}
  - put: dummy-bbr-script-release-bucket
    params:
      file: bbr-test-release-build/test-bosh-backup-and-restore-release-*.tgz
- name: deploy-bosh-directors
  serial: true
  plan:
  - get: bosh-backup-and-restore-meta
  - get: dummy-bbr-script-release-bucket
    trigger: true
    passed: [create-test-releases]
  - task: deploy-dev-bosh
    file: bosh-backup-and-restore-meta/ci/tasks/deploy-bosh-director.yml
    params:
      DIRECTOR_ENV: dev-bosh-director
      GIT_SSH_KEY: {{git-private-key}}
      GITHUB_PUBLIC_KEY: {{github-public-key}}
  - task: deploy-test-bosh
    file: bosh-backup-and-restore-meta/ci/tasks/deploy-bosh-director.yml
    params:
      DIRECTOR_ENV: test-bosh-director
      GIT_SSH_KEY: {{git-private-key}}
      GITHUB_PUBLIC_KEY: {{github-public-key}}

- name: upload-systest-releases
  serial: true
  plan:
  - get: bosh-backup-and-restore
    trigger: true
    params:
      submodules: none
      disable_git_lfs: true
  - get: bbr-systest-releases
    trigger: true
  - get: bosh-backup-and-restore-meta
  - aggregate:
    - task: upload-redis-test-release-lite-bosh
      file: bosh-backup-and-restore/ci/tasks/upload-systest-release.yml
      params:
        RELEASE_NAME: redis-test-release
        <<: *lite-bosh-env
    - task: upload-redis-test-release-maru-bosh
      file: bosh-backup-and-restore/ci/tasks/upload-systest-release.yml
      params:
        RELEASE_NAME: redis-test-release
        <<: *maru-bosh-env
    - task: upload-redis-test-release-lite-bosh-uaa
      file: bosh-backup-and-restore/ci/tasks/upload-systest-release.yml
      params:
        RELEASE_NAME: redis-test-release
        <<: *lite-bosh-uaa-env
    - task: upload-lock-ordering-release-lite-bosh
      file: bosh-backup-and-restore/ci/tasks/upload-systest-release.yml
      params:
        RELEASE_NAME: lock-ordering-release
        <<: *lite-bosh-env
    - task: upload-lock-ordering-release-lite-bosh-uaa
      file: bosh-backup-and-restore/ci/tasks/upload-systest-release.yml
      params:
        RELEASE_NAME: lock-ordering-release
        <<: *lite-bosh-uaa-env

- name: unit
  serial: true
  plan:
  - get: bosh-backup-and-restore
    trigger: true
    params:
      submodules: none
      disable_git_lfs: true
  - task: unit
    file: bosh-backup-and-restore/ci/tasks/unit.yml
    privileged: true
    params:
      DOCKER_HOST: "tcp://10.0.3.12:4243"
      GITHUB_SSH_KEY: "((github-ssh-key))"
- name: deploy-windows-vm
  serial: true
  plan:
  - aggregate:
    - get: windows-stemcell
    - get: ubuntu-stemcell
    - get: bosh-backup-and-restore
      passed: [unit]
      trigger: true
  - put: windows-vm-deployment
    params:
      manifest: bosh-backup-and-restore/fixtures/windows-vm.yml
      stemcells:
      - windows-stemcell/*.tgz
      - ubuntu-stemcell/*.tgz
  - put: jumpbox-windows-deployment
    params:
      manifest: bosh-backup-and-restore/fixtures/jumpbox-windows.yml
      stemcells:
      - ubuntu-stemcell/*.tgz
- name: system
  serial: true
  plan:
  - get: bosh-backup-and-restore
    passed: [unit, deploy-windows-vm, upload-systest-releases]
    trigger: true
  - get: bosh-backup-and-restore-meta
  - task: system
    file: bosh-backup-and-restore/ci/tasks/system.yml
    params:
      <<: *lite-bosh-env
- name: system-uaa
  serial: true
  plan:
  - get: bosh-backup-and-restore
    passed: [unit, upload-systest-releases]
    trigger: true
  - get: bosh-backup-and-restore-meta
  - task: system
    file: bosh-backup-and-restore/ci/tasks/system.yml
    params:
      <<: *lite-bosh-uaa-env
- name: system-director
  serial: true
  plan:
  - get: bosh-backup-and-restore
    passed: [unit, upload-systest-releases]
    trigger: true
  - get: bosh-backup-and-restore-meta
  - task: system-director
    file: bosh-backup-and-restore/ci/tasks/system-director.yml
    params:
      BOSH_ENVIRONMENT: genesis-bosh.backup-and-restore.cf-app.com
      BOSH_CLIENT_SECRET: ((genesis-bosh-director-password))
      HOST_TO_BACKUP: 10.0.0.7
- name: build-rc
  serial_groups: [version]
  plan:
  - get: bosh-backup-and-restore
    passed: [system, system-uaa, system-director]
    trigger: true
    params:
      submodules: none
      disable_git_lfs: true
  - get: version
    params: {pre: rc}
  - get: bosh-backup-and-restore-meta
  - task: build
    file: bosh-backup-and-restore/ci/tasks/build.yml
  - put: rc
    params: {file: bbr-build/bbr-*}
  - put: version
    params: {file: version/number}

- name: install-optional-components-on-pas
  serial: true
  plan:
  - aggregate:
    - get: pivotal-disaster-recovery-acceptance-tests
    - get: bosh-backup-and-restore
      passed: [build-rc]
      trigger: true
    - get: rc
      passed: [build-rc]
    - put: env-pool
      resource: pcf-2-1-pool
      params:
        action: claim
      tags:
      - *toolsmiths_api_worker
  - task: enable-internal-blobstore
    file: pivotal-disaster-recovery-acceptance-tests/ci/enable-internal-blobstore-pas/pool-task.yml
  - task: enable-optional-components
    file: pivotal-disaster-recovery-acceptance-tests/ci/enable-optional-components-pas/pool-task.yml
    privileged: true
    params:
      OPS_MAN_VERSION: "2.1"

- name: run-p-drats-on-pas
  serial: true
  plan:
  - get: pivotal-disaster-recovery-acceptance-tests
  - get: bosh-backup-and-restore
    passed: [install-optional-components-on-pas]
  - get: rc
    passed: [install-optional-components-on-pas]
    trigger: true
  - get: env-pool
    resource: pcf-2-1-pool
    passed: [install-optional-components-on-pas]
    tags:
    - *toolsmiths_api_worker
  - task: acceptance-tests
    tags:
    - *toolsmiths_pool_worker
    privileged: true
    file: pivotal-disaster-recovery-acceptance-tests/ci/p-drats-ops-manager/pool-task.yml
    input_mapping:
      bbr-binary-release: rc
    params:
      DEFAULT_TIMEOUT_MINS: 30
  - put: pcf-2-1-pool
    params:
      action: unclaim
      env_file: env-pool/metadata
    tags:
    - *toolsmiths_api_worker

- name: transfer-bbr-binary-to-jumpbox
  serial_groups: [version]
  plan:
    - get: bosh-backup-and-restore
      passed: [run-p-drats-on-pas]
      params:
        submodules: none
        disable_git_lfs: true
    - get: bosh-backup-and-restore-meta
    - get: rc
      passed: [run-p-drats-on-pas]
      trigger: true
    - task: transfer-bbr-binary-to-jumpbox
      file: bosh-backup-and-restore/ci/tasks/transfer-bbr-binary-to-jumpbox.yml
      params:
        BOSH_CLIENT_SECRET: ((genesis-bosh-director-password))
        BOSH_CLIENT: ((genesis-bosh-director-username))
        BOSH_TARGET: https://genesis-bosh.backup-and-restore.cf-app.com
- name: build-final
  serial_groups: [version]
  plan:
  - get: bosh-backup-and-restore-meta
    resource: release-trigger
    trigger: true
  - get: bosh-backup-and-restore
    passed: [run-p-drats-on-pas]
    params:
      submodules: none
      disable_git_lfs: true
  - task: get-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: cloudfoundrylondon/backup-and-restore}
      inputs:
      - name: bosh-backup-and-restore-meta
      outputs:
      - name: bbr-version
      run:
        path: /bin/bash
        args:
        - -c
        - |-
          set -eux
          cat bosh-backup-and-restore-meta/bbr-current-release/version > bbr-version/number
  - task: build
    file: bosh-backup-and-restore/ci/tasks/build.yml
    input_mapping: {version: bbr-version}
  - put: release
    params: {file: bbr-build/bbr-*}
  - put: version
    params: {file: bbr-version/number}
- name: publish-release
  serial: true
  plan:
  - aggregate:
    - get: bosh-backup-and-restore-meta
      resource: release-trigger
      passed: [build-final]
    - get: bosh-backup-and-restore
      passed: [build-final]
      params:
        submodules: none
        disable_git_lfs: true
    - get: release
      passed: [build-final]
      trigger: true
    - get: backup-and-restore-ci
  - task: generate-release-metadata
    file: backup-and-restore-ci/tasks/generate-release-metadata/task.yml
    input_mapping:
      release: release
      version-folder: bosh-backup-and-restore-meta
      template-folder: bosh-backup-and-restore-meta
    params:
      TEMPLATE_PATH: templates/release.yml.erb
      VERSION_PATH: bbr-current-release/version
  - task: generate-release-notes
    file: backup-and-restore-ci/tasks/generate-release-notes/task.yml
    input_mapping:
      repo: bosh-backup-and-restore
      template-folder: bosh-backup-and-restore-meta
    params:
      TEMPLATE_PATH: templates/release-notes.md.erb
  - put: bbr-pivnet
    params:
      metadata_file: release-with-metadata/release.yml
      s3_filepath_prefix: product-files/bosh-backup-restore
      file_glob: release-with-metadata/*.tar
  - put: bbr-release
    params:
      name: bosh-backup-and-restore-meta/bbr-current-release/version
      tag: bosh-backup-and-restore-meta/bbr-current-release/version
      tag_prefix: v
      body: release-notes/release-notes.md
      commitish: bosh-backup-and-restore/.git/refs/heads/master
      globs:
      - release-with-metadata/*.tar
