---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: terraform-state
- name: bosh-vars-store
- name: backup-and-restore-ci

params:
  BOSH_VARS_STORE_PATH:  # Path to bosh director vars-store YAML file
  BOSH_CLIENT:
  RESURRECTION:

run:
  path: backup-and-restore-ci/tasks/update-b-drats-resurrection/task.sh
