---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: bosh-backup-and-restore
- name: backup-and-restore-ci

params:
  DEPLOYMENT_NAME:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT:
  BOSH_GW_HOST:
  BOSH_GW_PRIVATE_KEY:
  BOSH_GW_USER:

run:
  path: backup-and-restore-ci/tasks/bbr-deploy-bosh-team/task.sh
