---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: latest

resources:
- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: bosh-disaster-recovery-acceptance-tests-prs
  type: pull-request
  source:
    repo: cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests
    access_token: ((github-access-token))
    branch: master

- name: bosh-disaster-recovery-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests.git
    branch: master

- name: bosh-backup-and-restore-meta
  type: git
  source:
    uri: git@github.com:pivotal-cf/bosh-backup-and-restore-meta.git
    private_key: ((git-private-key))
    branch: master

- name: backup-and-restore-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master

- name: bbr-binary-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github-access-token))

jobs:
- name: deploy-bosh-bengal-tiger
  serial: true
  serial_groups: [bengal-tiger]
  plan:
  - aggregate:
    - get: bosh-deployment
      trigger: true
    - get: bosh-disaster-recovery-acceptance-tests
      trigger: true
    - get: bosh-backup-and-restore-meta
    - get: backup-and-restore-ci
  - task: terraform-apply
    file: backup-and-restore-ci/tasks/terraform-operation/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
    params:
      ENVIRONMENT_NAME: b-drats-bengal-tiger
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      GIT_USER_NAME: "PCF Backup & Restore CI"
      GIT_USER_EMAIL: "cf-lazarus@pivotal.io"
    ensure:
      put: bosh-backup-and-restore-meta
      params:
        repository: terraform-state-updated
        rebase: true
  - task: bosh-create-env
    file: backup-and-restore-ci/tasks/bosh-create-env/task.yml
    input_mapping:
      bosh-state: bosh-backup-and-restore-meta
      terraform-state: bosh-backup-and-restore-meta
    params:
      ENVIRONMENT_NAME: "b-drats-bengal-tiger"
      BOSH_STATE_PREPARE_CMD: unlock-ci.sh
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      OPS_FILES: "gcp/cpi.yml external-ip-not-recommended.yml jumpbox-user.yml"
      DIRECTOR_NAME: "bengal-tiger"
    ensure:
      put: bosh-backup-and-restore-meta
      params:
        repository: bosh-state-updated
        rebase: true
  - task: update-b-drats-cloud-config
    file: backup-and-restore-ci/tasks/update-b-drats-cloud-config/task.yml
    input_mapping:
      cloud-config: bosh-deployment
      terraform-state: bosh-backup-and-restore-meta
      bosh-vars-store: bosh-backup-and-restore-meta
    params:
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      CLOUD_CONFIG_PATH: gcp/cloud-config.yml
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      BOSH_VARS_STORE_PREPARE_CMD: unlock-ci.sh
      TERRAFORM_STATE_PATH: b-drats-bengal-tiger/terraform.tfstate
      BOSH_VARS_STORE_PATH: b-drats-bengal-tiger/creds.yml
      BOSH_CLIENT: admin
  - task: upload-b-drats-stemcell
    file: backup-and-restore-ci/tasks/upload-b-drats-stemcell/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
      bosh-vars-store: bosh-backup-and-restore-meta
    params:
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      STEMCELL_URL: https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent?v=3586.7
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      BOSH_VARS_STORE_PREPARE_CMD: unlock-ci.sh
      TERRAFORM_STATE_PATH: b-drats-bengal-tiger/terraform.tfstate
      BOSH_VARS_STORE_PATH: b-drats-bengal-tiger/creds.yml
      BOSH_CLIENT: admin
  - task: update-b-drats-resurrection
    file: backup-and-restore-ci/tasks/update-b-drats-resurrection/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
      bosh-vars-store: bosh-backup-and-restore-meta
    params:
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      RESURRECTION: "off"
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      BOSH_VARS_STORE_PREPARE_CMD: unlock-ci.sh
      TERRAFORM_STATE_PATH: b-drats-bengal-tiger/terraform.tfstate
      BOSH_VARS_STORE_PATH: b-drats-bengal-tiger/creds.yml
      BOSH_CLIENT: admin

- name: deploy-bosh-black-panther
  serial: true
  serial_groups: [black-panther]
  plan:
  - aggregate:
    - get: bosh-deployment
      trigger: true
    - get: bosh-disaster-recovery-acceptance-tests-prs
      trigger: true
    - get: bosh-backup-and-restore-meta
    - get: backup-and-restore-ci
  - put: bosh-disaster-recovery-acceptance-tests-prs
    params:
      path: bosh-disaster-recovery-acceptance-tests-prs
      status: pending
      context: b-drats
  - task: terraform-apply
    file: backup-and-restore-ci/tasks/terraform-operation/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
    params:
      ENVIRONMENT_NAME: b-drats-black-panther
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      GIT_USER_NAME: "PCF Backup & Restore CI"
      GIT_USER_EMAIL: "cf-lazarus@pivotal.io"
    ensure:
      put: bosh-backup-and-restore-meta
      params:
        repository: terraform-state-updated
        rebase: true
    on_failure:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: failure
        context: b-drats
  - task: bosh-create-env
    file: backup-and-restore-ci/tasks/bosh-create-env/task.yml
    input_mapping:
      bosh-state: bosh-backup-and-restore-meta
      terraform-state: bosh-backup-and-restore-meta
    params:
      ENVIRONMENT_NAME: "b-drats-black-panther"
      BOSH_STATE_PREPARE_CMD: unlock-ci.sh
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      OPS_FILES: "gcp/cpi.yml external-ip-not-recommended.yml jumpbox-user.yml"
      DIRECTOR_NAME: "black-panther"
    ensure:
      put: bosh-backup-and-restore-meta
      params:
        repository: bosh-state-updated
        rebase: true
    on_failure:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: failure
        context: b-drats
  - task: update-b-drats-cloud-config
    file: backup-and-restore-ci/tasks/update-b-drats-cloud-config/task.yml
    input_mapping:
      cloud-config: bosh-deployment
      terraform-state: bosh-backup-and-restore-meta
      bosh-vars-store: bosh-backup-and-restore-meta
    params:
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      CLOUD_CONFIG_PATH: gcp/cloud-config.yml
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      BOSH_VARS_STORE_PREPARE_CMD: unlock-ci.sh
      TERRAFORM_STATE_PATH: b-drats-black-panther/terraform.tfstate
      BOSH_VARS_STORE_PATH: b-drats-black-panther/creds.yml
      BOSH_CLIENT: admin
    on_failure:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: failure
        context: b-drats
  - task: upload-b-drats-stemcell
    file: backup-and-restore-ci/tasks/upload-b-drats-stemcell/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
      bosh-vars-store: bosh-backup-and-restore-meta
    params:
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      STEMCELL_URL: https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent?v=3586.7
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      BOSH_VARS_STORE_PREPARE_CMD: unlock-ci.sh
      TERRAFORM_STATE_PATH: b-drats-black-panther/terraform.tfstate
      BOSH_VARS_STORE_PATH: b-drats-black-panther/creds.yml
      BOSH_CLIENT: admin
    on_failure:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: failure
        context: b-drats
  - task: update-b-drats-resurrection
    file: backup-and-restore-ci/tasks/update-b-drats-resurrection/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
      bosh-vars-store: bosh-backup-and-restore-meta
    params:
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      RESURRECTION: "off"
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      BOSH_VARS_STORE_PREPARE_CMD: unlock-ci.sh
      TERRAFORM_STATE_PATH: b-drats-black-panther/terraform.tfstate
      BOSH_VARS_STORE_PATH: b-drats-black-panther/creds.yml
      BOSH_CLIENT: admin
    on_failure:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: failure
        context: b-drats

- name: run-b-drats-master
  serial: true
  serial_groups: [bengal-tiger]
  plan:
  - aggregate:
    - get: bosh-disaster-recovery-acceptance-tests
      passed: [deploy-bosh-bengal-tiger]
      trigger: true
    - get: bosh-deployment
      passed: [deploy-bosh-bengal-tiger]
      trigger: true
    - get: bbr-binary-release
      trigger: true
    - get: bosh-backup-and-restore-meta
    - get: backup-and-restore-ci
  - task: extract-b-drats-integration-config
    file: backup-and-restore-ci/tasks/extract-b-drats-integration-config/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
      bosh-vars-store: bosh-backup-and-restore-meta
    params:
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      TERRAFORM_STATE_PREPARE_CMD: terraform-state/unlock-ci.sh
      BOSH_VARS_STORE_PREPARE_CMD: bosh-vars-store/unlock-ci.sh
      TERRAFORM_STATE_PATH: terraform-state/b-drats-bengal-tiger/terraform.tfstate
      BOSH_VARS_STORE_PATH: bosh-vars-store/b-drats-bengal-tiger/creds.yml
  - task: run-b-drats
    file: bosh-disaster-recovery-acceptance-tests/ci/run-b-drats/task.yml
    params:
      INTEGRATION_CONFIG_PATH: b-drats-integration-config/integration_config.json

- name: run-b-drats-prs
  serial: true
  serial_groups: [black-panther]
  plan:
  - aggregate:
    - get: bosh-disaster-recovery-acceptance-tests-prs
      passed: [deploy-bosh-black-panther]
      trigger: true
    - get: bosh-deployment
      passed: [deploy-bosh-black-panther]
      trigger: true
    - get: bbr-binary-release
      trigger: true
    - get: bosh-backup-and-restore-meta
    - get: backup-and-restore-ci
  - put: bosh-disaster-recovery-acceptance-tests-prs
    params:
      path: bosh-disaster-recovery-acceptance-tests-prs
      status: pending
      context: b-drats
  - task: extract-b-drats-integration-config
    file: backup-and-restore-ci/tasks/extract-b-drats-integration-config/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
      bosh-vars-store: bosh-backup-and-restore-meta
    params:
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      TERRAFORM_STATE_PREPARE_CMD: terraform-state/unlock-ci.sh
      BOSH_VARS_STORE_PREPARE_CMD: bosh-vars-store/unlock-ci.sh
      TERRAFORM_STATE_PATH: terraform-state/b-drats-black-panther/terraform.tfstate
      BOSH_VARS_STORE_PATH: bosh-vars-store/b-drats-black-panther/creds.yml
    on_failure:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: failure
        context: b-drats
  - task: run-b-drats
    file: bosh-disaster-recovery-acceptance-tests-prs/ci/run-b-drats/task.yml
    params:
      INTEGRATION_CONFIG_PATH: b-drats-integration-config/integration_config.json
    input_mapping:
      bosh-disaster-recovery-acceptance-tests: bosh-disaster-recovery-acceptance-tests-prs
    on_failure:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: failure
        context: b-drats
    on_success:
      put: bosh-disaster-recovery-acceptance-tests-prs
      params:
        path: bosh-disaster-recovery-acceptance-tests-prs
        status: success
        context: b-drats
