---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: terraform-state

params:
  APP_ID:
  PASSWORD:
  TENANT_ID:

run:
  path: backup-and-restore-ci/tasks/enable-soft-delete-azure/task.sh
