---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: version
- name: bosh-backup-and-restore
  path: src/github.com/cloudfoundry-incubator/bosh-backup-and-restore
- name: bosh-backup-and-restore-meta
- name: backup-and-restore-ci

outputs:
- name: bbr-build

run:
  path: backup-and-restore-ci/tasks/bbr-build/task.sh
