---
opsman_credentials: &opsman_credentials
  SKIP_SSL_VALIDATION: ((skip-ssl-validation))
  OPSMAN_URL: ((opsman-url))
  OPSMAN_USERNAME: ((opsman-username))
  OPSMAN_PASSWORD: ((opsman-password))

s3_credentials: &s3_credentials
  bucket: ((storage-backup-bucket))
  region_name: ((storage-region))
  access_key_id: ((storage-access-key-id))
  secret_access_key: ((storage-secret-access-key))
  endpoint: ((storage-endpoint))

groups:
- name: master
  jobs:
  - export-om-installation
  - bbr-backup-director
  - bbr-backup-ert

- name: pull-requests
  jobs:
  - validate-sample-pipeline-prs
  - export-om-installation-prs
  - bbr-backup-director-prs
  - bbr-cleanup-director-prs
  - bbr-backup-ert-prs
  - bbr-cleanup-ert-prs

jobs:
- name: export-om-installation
  serial: true
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
  - task: export-om-installation
    file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    params:
      OPSMAN_PASSWORD: ((opsman-password))
      OPSMAN_URL: ((opsman-url))
      OPSMAN_USERNAME: ((opsman-username))
      SKIP_SSL_VALIDATION: ((skip-ssl-validation))
  - put: om-backup-artifact
    params:
      file: om-installation/installation.zip

- name: bbr-backup-ert
  serial: true
  serial_groups:
  - backup-ert
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
    - get: bbr-release
      trigger: true
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
  - task: bbr-backup-ert
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-ert/task.yml
    params:
      <<: *opsman_credentials
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    tags:
    - ((concourse-worker-tag))
    on_failure:
      task: bbr-cleanup-ert
      file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-ert/task.yml
      params:
        <<: *opsman_credentials
        OPSMAN_PRIVATE_KEY: ((opsman-private-key))
  - put: ert-backup-bucket
    params:
      file: ert-backup-artifact/ert-backup.tar

- name: bbr-backup-director
  serial: true
  serial_groups:
  - backup-director
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
    - get: bbr-release
      trigger: true
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
  - task: bbr-backup-director
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.yml
    params:
      <<: *opsman_credentials
    tags:
    - ((concourse-worker-tag))
    on_failure:
      task: bbr-cleanup-director
      file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-director/task.yml
      params:
        <<: *opsman_credentials
      tags:
      - ((concourse-worker-tag))
  - put: director-backup-bucket
    params:
      file: director-backup-artifact/director-backup.tar

- name: validate-sample-pipeline-prs
  plan:
  - get: bbr-pipeline-tasks-repo
    trigger: true
    resource: bbr-pipeline-tasks-prs
  - put: bbr-pipeline-tasks-prs
    params:
      context: validation-of-sample-pipeline
      path: bbr-pipeline-tasks-repo
      status: pending
  - task: validate-pipeline-with-secrets
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundrylondon/bbr-pipeline
          tag: final
      inputs:
      - name: bbr-pipeline-tasks-repo
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          bosh int bbr-pipeline-tasks-repo/pas-pipeline.sample.yml -l bbr-pipeline-tasks-repo/pas-secrets.sample.yml --var-errs --var-errs-unused
          fly validate-pipeline -c bbr-pipeline-tasks-repo/pas-pipeline.sample.yml -l bbr-pipeline-tasks-repo/pas-secrets.sample.yml
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: validation-of-sample-pipeline
        path: bbr-pipeline-tasks-repo
        status: failure
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: validation-of-sample-pipeline
        path: bbr-pipeline-tasks-repo
        status: success

- name: export-om-installation-prs
  serial: true
  plan:
  - get: bbr-pipeline-tasks-repo
    trigger: true
    resource: bbr-pipeline-tasks-prs
  - put: bbr-pipeline-tasks-prs
    params:
      context: export-om-installation
      path: bbr-pipeline-tasks-repo
      status: pending
  - task: export-om-installation
    file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    params:
      <<: *opsman_credentials
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: export-om-installation
        path: bbr-pipeline-tasks-repo
        status: failure
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: export-om-installation
        path: bbr-pipeline-tasks-repo
        status: success
  - put: om-backup-artifact
    params:
      file: om-installation/installation.zip

- name: bbr-backup-ert-prs
  serial: true
  serial_groups:
  - backup-ert
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
      resource: bbr-pipeline-tasks-prs
    - get: bbr-release
  - put: bbr-pipeline-tasks-prs
    params:
      context: bbr-backup-ert
      path: bbr-pipeline-tasks-repo
      status: pending
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
  - task: bbr-backup-ert
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-ert/task.yml
    params:
      <<: *opsman_credentials
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    tags:
    - ((concourse-worker-tag))
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: bbr-backup-ert
        path: bbr-pipeline-tasks-repo
        status: failure
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: bbr-backup-ert
        path: bbr-pipeline-tasks-repo
        status: success
  - put: ert-backup-bucket
    params:
      file: ert-backup-artifact/ert-backup.tar

- name: bbr-backup-director-prs
  serial: true
  serial_groups:
  - backup-director
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
      resource: bbr-pipeline-tasks-prs
    - get: bbr-release
  - put: bbr-pipeline-tasks-prs
    params:
      context: bbr-backup-director
      path: bbr-pipeline-tasks-repo
      status: pending
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
  - task: bbr-backup-director
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.yml
    params:
      <<: *opsman_credentials
    tags:
    - ((concourse-worker-tag))
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: bbr-backup-director
        path: bbr-pipeline-tasks-repo
        status: failure
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: bbr-backup-director
        path: bbr-pipeline-tasks-repo
        status: success
  - put: director-backup-bucket
    params:
      file: director-backup-artifact/director-backup.tar

- name: bbr-cleanup-ert-prs
  serial: true
  serial_groups:
  - backup-ert
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-prs
      trigger: true
    - get: bbr-release
  - task: extract-binary
    file: bbr-pipeline-tasks-prs/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
  - task: bbr-cleanup-ert-prs
    file: bbr-pipeline-tasks-prs/tasks/bbr-cleanup-ert/task.yml
    params:
      <<: *opsman_credentials
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    input_mapping:
      bbr-pipeline-tasks-repo: bbr-pipeline-tasks-prs
    tags:
    - ((concourse-worker-tag))
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: bbr-cleanup-ert
        path: bbr-pipeline-tasks-prs
        status: failure
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: bbr-cleanup-ert
        path: bbr-pipeline-tasks-prs
        status: success

- name: bbr-cleanup-director-prs
  serial: true
  serial_groups:
  - backup-director
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-prs
      trigger: true
    - get: bbr-release
  - task: extract-binary
    file: bbr-pipeline-tasks-prs/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
  - task: bbr-cleanup-director-prs
    file: bbr-pipeline-tasks-prs/tasks/bbr-cleanup-director/task.yml
    params:
      <<: *opsman_credentials
    input_mapping:
      bbr-pipeline-tasks-repo: bbr-pipeline-tasks-prs
    tags:
    - ((concourse-worker-tag))
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: bbr-cleanup-director
        path: bbr-pipeline-tasks-prs
        status: failure
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: bbr-cleanup-director
        path: bbr-pipeline-tasks-prs
        status: success

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: latest

resources:
- name: bbr-pipeline-tasks-repo
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks.git

- name: bbr-pipeline-tasks-prs
  type: pull-request
  source:
    access_token: ((github-access-token))
    private_key: ((git-private-key))
    repo: pivotal-cf/bbr-pcf-pipeline-tasks
    uri: git@github.com:pivotal-cf/bbr-pcf-pipeline-tasks.git

- name: om-backup-artifact
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: installation.zip

- name: ert-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: ert-backup.tar

- name: director-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: director-backup.tar

- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-bosh-backup-and-restore
