---
opsman_credentials: &opsman_credentials
  SKIP_SSL_VALIDATION: ((skip-ssl-validation))
  OPSMAN_URL: ((opsman-url))
  OPSMAN_USERNAME: ((opsman-username))
  OPSMAN_PASSWORD: ((opsman-password))

s3_credentials: &s3_credentials
  bucket: ((storage-backup-bucket))
  region_name: ((storage-region))
  access_key_id: ((storage-access-key-id))
  secret_access_key: ((storage-secret-access-key))
  endpoint: ((storage-endpoint))

groups:
- name: master
  jobs:
  - export-om-installation
  - bbr-backup-director
  - bbr-backup-ert

- name: pull-requests
  jobs:
  - export-om-installation-prs
  - bbr-backup-director-prs
  - bbr-cleanup-director-prs
  - bbr-backup-ert-prs
  - bbr-cleanup-ert-prs

jobs:
- name: export-om-installation
  serial: true
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
  - file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    params:
      <<: *opsman_credentials
    task: export-om-installation
  - params:
      file: om-installation/installation.zip
    put: om-backup-artifact

- name: bbr-backup-ert
  serial: true
  serial_groups:
  - backup-ert
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
    - get: bbr-release
      trigger: true
  - file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
    task: extract-binary
  - file: bbr-pipeline-tasks-repo/tasks/bbr-backup-ert/task.yml
    on_failure:
      file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-ert/task.yml
      params:
        <<: *opsman_credentials
        OPSMAN_PRIVATE_KEY: ((opsman-private-key))
      task: bbr-cleanup-ert
    params:
      <<: *opsman_credentials
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    tags:
    - ((concourse-worker-tag))
    task: bbr-backup-ert
  - params:
      file: ert-backup-artifact/ert-backup.tar
    put: ert-backup-bucket

- name: bbr-backup-director
  serial: true
  serial_groups:
  - backup-director
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
    - get: bbr-release
      trigger: true
  - file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
    task: extract-binary
  - file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.yml
    on_failure:
      file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-director/task.yml
      params:
        <<: *opsman_credentials
      tags:
      - ((concourse-worker-tag))
      task: bbr-cleanup-director
    params:
      <<: *opsman_credentials
    tags:
    - ((concourse-worker-tag))
    task: bbr-backup-director
  - params:
      file: director-backup-artifact/director-backup.tar
    put: director-backup-bucket

- name: export-om-installation-prs
  serial: true
  plan:
  - get: bbr-pipeline-tasks-repo
    resource: bbr-pipeline-tasks-prs
    trigger: true
  - params:
      context: export-om-installation
      path: bbr-pipeline-tasks-repo
      status: pending
    put: bbr-pipeline-tasks-prs
  - file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    on_failure:
      params:
        context: export-om-installation
        path: bbr-pipeline-tasks-repo
        status: failure
      put: bbr-pipeline-tasks-prs
    on_success:
      params:
        context: export-om-installation
        path: bbr-pipeline-tasks-repo
        status: success
      put: bbr-pipeline-tasks-prs
    params:
      <<: *opsman_credentials
    task: export-om-installation
  - params:
      file: om-installation/installation.zip
    put: om-backup-artifact

- name: bbr-backup-ert-prs
  serial: true
  serial_groups:
  - backup-ert
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      resource: bbr-pipeline-tasks-prs
      trigger: true
    - get: bbr-release
  - params:
      context: bbr-backup-ert
      path: bbr-pipeline-tasks-repo
      status: pending
    put: bbr-pipeline-tasks-prs
  - file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
    task: extract-binary
  - file: bbr-pipeline-tasks-repo/tasks/bbr-backup-ert/task.yml
    on_failure:
      params:
        context: bbr-backup-ert
        path: bbr-pipeline-tasks-repo
        status: failure
      put: bbr-pipeline-tasks-prs
    on_success:
      params:
        context: bbr-backup-ert
        path: bbr-pipeline-tasks-repo
        status: success
      put: bbr-pipeline-tasks-prs
    params:
      <<: *opsman_credentials
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    tags:
    - ((concourse-worker-tag))
    task: bbr-backup-ert
  - params:
      file: ert-backup-artifact/ert-backup.tar
    put: ert-backup-bucket

- name: bbr-backup-director-prs
  serial: true
  serial_groups:
  - backup-director
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      resource: bbr-pipeline-tasks-prs
      trigger: true
    - get: bbr-release
  - params:
      context: bbr-backup-director
      path: bbr-pipeline-tasks-repo
      status: pending
    put: bbr-pipeline-tasks-prs
  - file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
    task: extract-binary
  - file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.yml
    on_failure:
      params:
        context: bbr-backup-director
        path: bbr-pipeline-tasks-repo
        status: failure
      put: bbr-pipeline-tasks-prs
    on_success:
      params:
        context: bbr-backup-director
        path: bbr-pipeline-tasks-repo
        status: success
      put: bbr-pipeline-tasks-prs
    params:
      <<: *opsman_credentials
    tags:
    - ((concourse-worker-tag))
    task: bbr-backup-director
  - params:
      file: director-backup-artifact/director-backup.tar
    put: director-backup-bucket

- name: bbr-cleanup-ert-prs
  serial: true
  serial_groups:
  - backup-ert
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-prs
      trigger: true
    - get: bbr-release
  - file: bbr-pipeline-tasks-prs/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
    task: extract-binary
  - file: bbr-pipeline-tasks-prs/tasks/bbr-cleanup-ert/task.yml
    input_mapping:
      bbr-pipeline-tasks-repo: bbr-pipeline-tasks-prs
    on_failure:
      params:
        context: bbr-cleanup-ert
        path: bbr-pipeline-tasks-prs
        status: failure
      put: bbr-pipeline-tasks-prs
    on_success:
      params:
        context: bbr-cleanup-ert
        path: bbr-pipeline-tasks-prs
        status: success
      put: bbr-pipeline-tasks-prs
    params:
      <<: *opsman_credentials
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    tags:
    - ((concourse-worker-tag))
    task: bbr-cleanup-ert-prs

- name: bbr-cleanup-director-prs
  serial: true
  serial_groups:
  - backup-director
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-prs
      trigger: true
    - get: bbr-release
  - file: bbr-pipeline-tasks-prs/tasks/extract-bbr-binary/task.yml
    tags:
    - ((concourse-worker-tag))
    task: extract-binary
  - file: bbr-pipeline-tasks-prs/tasks/bbr-cleanup-director/task.yml
    input_mapping:
      bbr-pipeline-tasks-repo: bbr-pipeline-tasks-prs
    on_failure:
      params:
        context: bbr-cleanup-director
        path: bbr-pipeline-tasks-prs
        status: failure
      put: bbr-pipeline-tasks-prs
    on_success:
      params:
        context: bbr-cleanup-director
        path: bbr-pipeline-tasks-prs
        status: success
      put: bbr-pipeline-tasks-prs
    params:
      <<: *opsman_credentials
    tags:
    - ((concourse-worker-tag))
    task: bbr-cleanup-director-prs

resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
- name: pull-request
  source:
    repository: jtarchie/pr
    tag: latest
  type: docker-image

resources:
- name: bbr-pipeline-tasks-repo
  source:
    branch: master
    uri: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks.git
  type: git

- name: bbr-pipeline-tasks-prs
  type: pull-request
  source:
    access_token: ((github-access-token))
    private_key: ((git-private-key))
    repo: pivotal-cf/bbr-pcf-pipeline-tasks
    uri: git@github.com:pivotal-cf/bbr-pcf-pipeline-tasks.git

- name: om-backup-artifact
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: installation.zip

- name: ert-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: ert-backup.tar

- name: director-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: director-backup.tar

- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-bosh-backup-and-restore
