---
resources:
- name: cfops-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master
    paths: ["ci-docker-images/cfops/*"]

- name: cfops-docs-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master
    paths: ["ci-docker-images/cfops-docs/*"]

- name: backup-and-restore-minimal-repo
  type: git
  source:
    private_key: ((git-private-key))
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    branch: master
    paths: ["ci-docker-images/backup-and-restore-minimal/*"]

- name: bosh-backup-and-restore-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master
    paths: ["ci-docker-images/bosh-backup-and-restore/*"]

- name: bosh-lite-stemcell-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master
    paths: ["ci-docker-images/bosh-lite-stemcell"]

- name: backup-and-restore-node-with-ssh-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master
    paths: ["ci-docker-images/backup-and-restore-node-with-ssh/*"]

- name: k-drats
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master
    paths: ["ci-docker-images/k-drats/*"]

- name: cfops-docker-image
  type: docker-image
  source:
    repository: cloudfoundrylondon/cfops
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: cfops-docs-docker-image
  type: docker-image
  source:
    repository: cloudfoundrylondon/cfops-docs
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: backup-and-restore-minimal-docker-image
  type: docker-image
  source:
    repository: cloudfoundrylondon/backup-and-restore-minimal
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: bosh-backup-and-restore-docker-image
  type: docker-image
  source:
    repository: cloudfoundrylondon/backup-and-restore
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: bosh-lite-stemcell-docker-image
  source:
    repository: cloudfoundrylondon/backup-and-restore-bosh-stemcell
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: backup-and-restore-node-with-ssh-docker-image
  type: docker-image
  source:
    repository: cloudfoundrylondon/backup-and-restore-node-with-ssh
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: cf-deployment-concourse-tasks-docker-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: k-drats-docker-image
  type: docker-image
  source:
    repository: cloudfoundrylondon/k-drats
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: golang-docker-image
  type: docker-image
  source:
    repository: golang
    username: ((dockerhub-username))
    password: ((dockerhub-password))
    tag: 1

jobs:
- name: build-cfops
  public: true
  serial: true
  plan:
  - get: cfops-repo
    trigger: true
  - put: cfops-docker-image
    params:
      build: cfops-repo/ci-docker-images/cfops/

- name: build-cfops-docs
  public: true
  serial: true
  plan:
  - get: cfops-docs-repo
    trigger: true
  - put: cfops-docs-docker-image
    params:
      build: cfops-docs-repo/ci-docker-images/cfops-docs/

- name: build-k-drats
  public: true
  serial: true
  plan:
  - aggregate:
    - get: k-drats
      trigger: true
    - get: cf-deployment-concourse-tasks-docker-image
      trigger: true
  - put: k-drats-docker-image
    params:
      build: k-drats/ci-docker-images/k-drats/

- name: build-backup-and-restore-minimal
  public: true
  serial: true
  plan:
  - aggregate:
    - get: golang-docker-image
      trigger: true
    - get: backup-and-restore-minimal-repo
      trigger: true
  - put: backup-and-restore-minimal-docker-image
    params:
      build: backup-and-restore-minimal-repo/ci-docker-images/backup-and-restore-minimal/

- name: build-bosh-backup-and-restore
  public: true
  serial: true
  plan:
  - get: bosh-backup-and-restore-repo
    trigger: true
  - get: backup-and-restore-minimal-docker-image
    trigger: true
    passed: [build-backup-and-restore-minimal]
  - put: bosh-backup-and-restore-docker-image
    params:
      build: bosh-backup-and-restore-repo/ci-docker-images/bosh-backup-and-restore/

- name: build-bosh-lite-stemcell
  serial: true
  plan:
  - get: bosh-lite-stemcell-repo
    trigger: true
  - task: make-and-push-bosh-lite-stemcell
    privileged: true
    params:
      DOCKER_HOST: "tcp://10.0.3.12:4243"
      DOCKER_USERNAME: ((dockerhub-username))
      DOCKER_PASSWORD: ((dockerhub-password))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: cloudfoundrylondon/backup-and-restore}
      inputs:
        - name: bosh-lite-stemcell-repo
      run:
        path: bash
        args:
        - -uc
        - ./bosh-lite-stemcell-repo/ci-docker-images/bosh-lite-stemcell/make_and_push_bosh_stemcell.sh

- name: build-backup-and-restore-node-with-ssh
  public: true
  serial: true
  plan:
  - get: backup-and-restore-node-with-ssh-repo
    trigger: true
  - get: bosh-lite-stemcell-docker-image
    trigger: true
  - put: backup-and-restore-node-with-ssh-docker-image
    params:
      build: backup-and-restore-node-with-ssh-repo/ci-docker-images/backup-and-restore-node-with-ssh/
