---
groups:
- name: BBR-PKS-BACKUP
  jobs:
  - export-om-installation
  - lock-pks
  - bbr-backup-director
  - bbr-backup-pks
  - bbr-backup-pks-clusters
  - unlock-pks

jobs:
- name: export-om-installation
  serial: true
  plan:
  - aggregate:
    - get: bbr-release
      trigger: true
    - get: bbr-pipeline-tasks-repo
      trigger: true
  - task: export-om-installation
    file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    params:
      SKIP_SSL_VALIDATION: ((skip-ssl-validation))
      OPSMAN_URL: ((opsman-url))
      OPSMAN_USERNAME: ((opsman-username))
      OPSMAN_PASSWORD: ((opsman-password))
  - put: om-backup-bucket
    params:
      file: om-installation/installation.zip

- name: lock-pks
  serial: true
  plan:
  - aggregate:
    - get: bbr-release
      trigger: true
      passed: [export-om-installation]
    - get: bbr-pipeline-tasks-repo
      trigger: true
      passed: [export-om-installation]
  - task: lock-pks
    file: bbr-pipeline-tasks-repo/tasks/lock-pks/task.yml
    params:
      SKIP_SSL_VALIDATION: ((skip-ssl-validation))
      OPSMAN_URL: ((opsman-url))
      OPSMAN_USERNAME: ((opsman-username))
      OPSMAN_PASSWORD: ((opsman-password))
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))


- name: bbr-backup-director
  serial: true
  plan:
  - aggregate:
    - get: bbr-release
      trigger: true
      passed: [lock-pks]
    - get: bbr-pipeline-tasks-repo
      trigger: true
      passed: [lock-pks]
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
  - task: bbr-backup-director
    privileged: true
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.yml
    params:
      SKIP_SSL_VALIDATION: ((skip-ssl-validation))
      OPSMAN_URL: ((opsman-url))
      OPSMAN_USERNAME: ((opsman-username))
      OPSMAN_PASSWORD: ((opsman-password))
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    on_failure:
      aggregate:
      - task: bbr-cleanup-director
        file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-director/task.yml
        params:
          SKIP_SSL_VALIDATION: ((skip-ssl-validation))
          OPSMAN_URL: ((opsman-url))
          OPSMAN_USERNAME: ((opsman-username))
          OPSMAN_PASSWORD: ((opsman-password))
          OPSMAN_PRIVATE_KEY: ((opsman-private-key))
      - task: unlock-pks
        file: bbr-pipeline-tasks-repo/tasks/unlock-pks/task.yml
        params:
          SKIP_SSL_VALIDATION: ((skip-ssl-validation))
          OPSMAN_URL: ((opsman-url))
          OPSMAN_USERNAME: ((opsman-username))
          OPSMAN_PASSWORD: ((opsman-password))
          OPSMAN_PRIVATE_KEY: ((opsman-private-key))
  - put: director-backup-bucket
    params:
      file: director-backup-artifact/director-backup.tar

- name: bbr-backup-pks
  serial: true
  plan:
  - aggregate:
    - get: bbr-release
      trigger: true
      passed: [bbr-backup-director]
    - get: bbr-pipeline-tasks-repo
      trigger: true
      passed: [bbr-backup-director]
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
  - task: bbr-backup-pks
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-pks/task.yml
    params:
      SKIP_SSL_VALIDATION: ((skip-ssl-validation))
      OPSMAN_URL: ((opsman-url))
      OPSMAN_USERNAME: ((opsman-username))
      OPSMAN_PASSWORD: ((opsman-password))
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    on_failure:
      aggregate:
      - task: bbr-cleanup-pks
        file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pks/task.yml
        params:
          SKIP_SSL_VALIDATION: ((skip-ssl-validation))
          OPSMAN_URL: ((opsman-url))
          OPSMAN_USERNAME: ((opsman-username))
          OPSMAN_PASSWORD: ((opsman-password))
          OPSMAN_PRIVATE_KEY: ((opsman-private-key))
      - task: unlock-pks
        file: bbr-pipeline-tasks-repo/tasks/unlock-pks/task.yml
        params:
          SKIP_SSL_VALIDATION: ((skip-ssl-validation))
          OPSMAN_URL: ((opsman-url))
          OPSMAN_USERNAME: ((opsman-username))
          OPSMAN_PASSWORD: ((opsman-password))
          OPSMAN_PRIVATE_KEY: ((opsman-private-key))
  - put: pks-backup-bucket
    params:
      file: pks-backup-artifact/pks-backup.tar

- name: bbr-backup-pks-clusters
  serial: true
  plan:
  - aggregate:
    - get: bbr-release
      trigger: true
      passed: [bbr-backup-pks]
    - get: bbr-pipeline-tasks-repo
      trigger: true
      passed: [bbr-backup-pks]
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
  - task: bbr-backup-pks-clusters
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-pks-clusters/task.yml
    params:
      SKIP_SSL_VALIDATION: ((skip-ssl-validation))
      OPSMAN_URL: ((opsman-url))
      OPSMAN_USERNAME: ((opsman-username))
      OPSMAN_PASSWORD: ((opsman-password))
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))
    on_failure:
      aggregate:
      - task: unlock-pks
        file: bbr-pipeline-tasks-repo/tasks/unlock-pks/task.yml
        params:
          SKIP_SSL_VALIDATION: ((skip-ssl-validation))
          OPSMAN_URL: ((opsman-url))
          OPSMAN_USERNAME: ((opsman-username))
          OPSMAN_PASSWORD: ((opsman-password))
          OPSMAN_PRIVATE_KEY: ((opsman-private-key))
      - task: bbr-cleanup-pks-clusters
        file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pks-clusters/task.yml
        params:
          SKIP_SSL_VALIDATION: ((skip-ssl-validation))
          OPSMAN_URL: ((opsman-url))
          OPSMAN_USERNAME: ((opsman-username))
          OPSMAN_PASSWORD: ((opsman-password))
          OPSMAN_PRIVATE_KEY: ((opsman-private-key))
  - put: pks-backup-bucket
    params:
      file: pks-clusters-backup-artifact/pks-clusters-backup.tar

- name: unlock-pks
  serial: true
  plan:
  - aggregate:
    - get: bbr-release
      trigger: true
      passed: [bbr-backup-pks-clusters]
    - get: bbr-pipeline-tasks-repo
      trigger: true
      passed: [bbr-backup-pks-clusters]
  - task: unlock-pks
    file: bbr-pipeline-tasks-repo/tasks/unlock-pks/task.yml
    params:
      SKIP_SSL_VALIDATION: ((skip-ssl-validation))
      OPSMAN_URL: ((opsman-url))
      OPSMAN_USERNAME: ((opsman-username))
      OPSMAN_PASSWORD: ((opsman-password))
      OPSMAN_PRIVATE_KEY: ((opsman-private-key))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: bbr-pipeline-tasks-repo
  type: git
  source:
    uri: git@github.com:pivotal-cf/bbr-pcf-pipeline-tasks.git
    private_key: ((git-private-key))
    branch: master

- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-bosh-backup-and-restore

- name: om-backup-bucket
  type: s3
  source: &S3_CREDS
    versioned_file: installation.zip
    bucket: ((aws-backup-bucket))
    region_name: ((aws-backup-bucket-region))
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))

- name: director-backup-bucket
  type: s3
  source:
    <<: *S3_CREDS
    versioned_file: director-backup.tar

- name: pks-backup-bucket
  type: s3
  source:
    <<: *S3_CREDS
    versioned_file: pks-backup.tar