---
opsman_credentials: &opsman_credentials
  SKIP_SSL_VALIDATION: ((skip-ssl-validation))
  OPSMAN_URL: ((opsman-url))
  OPSMAN_USERNAME: ((opsman-username))
  OPSMAN_PASSWORD: ((opsman-password))
  OPSMAN_PRIVATE_KEY: ((opsman-private-key))

s3_credentials: &s3_credentials
  bucket: ((storage-backup-bucket))
  region_name: ((storage-region))
  access_key_id: ((storage-access-key-id))
  secret_access_key: ((storage-secret-access-key))
  endpoint: ((storage-endpoint))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: latest

resources:
- name: backup-and-restore-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/backup-and-restore-ci.git
    branch: master
    private_key: ((git-private-key))

- name: bbr-pipeline-tasks-repo
  type: git
  source:
    uri: git@github.com:pivotal-cf/bbr-pcf-pipeline-tasks.git
    private_key: ((git-private-key))
    branch: master
    ignore_paths:
    - docker/*
    - README.md
    - tasks/bbr-backup-ert/*
    - tasks/bbr-cleanup-ert/*

- name: bbr-pipeline-tasks-prs
  type: pull-request
  source:
    access_token: ((github-access-token))
    private_key: ((git-private-key))
    repo: pivotal-cf/bbr-pcf-pipeline-tasks
    uri: git@github.com:pivotal-cf/bbr-pcf-pipeline-tasks.git
    ignore_paths:
    - docker/*
    - README.md
    - tasks/bbr-backup-ert/*
    - tasks/bbr-cleanup-ert/*
    - tasks/bbr-backup-director/*
    - tasks/bbr-cleanup-director/*
    - tasks/export-om-installation/*

- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-bosh-backup-and-restore

- name: om-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: installation.zip

- name: director-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: director-backup.tar

- name: pks-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: pks-backup.tar

groups:
- name: master
  jobs:
  - export-om-installation
  - bbr-backup-pks-foundation
  - validate-sample-pipeline

- name: pull-requests
  jobs:
  - bbr-backup-pks-foundation-prs
  - validate-sample-pipeline-prs


jobs:
- name: validate-sample-pipeline
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
    - get: backup-and-restore-ci
  - task: validate-pipeline
    file: backup-and-restore-ci/tasks/validate-pipeline/task.yml
    input_mapping:
      pipeline: bbr-pipeline-tasks-repo
    params:
      PIPELINE_PATH: examples/pks-pipeline.yml
      SECRETS_PATH: examples/pks-secrets.yml

- name: export-om-installation
  serial: true
  plan:
  - aggregate:
    - get: bbr-release
      trigger: true
    - get: bbr-pipeline-tasks-repo
      trigger: true
  - task: export-om-installation
    file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    params:
      SKIP_SSL_VALIDATION: ((skip-ssl-validation))
      OPSMAN_URL: ((opsman-url))
      OPSMAN_USERNAME: ((opsman-username))
      OPSMAN_PASSWORD: ((opsman-password))
  - put: om-backup-bucket
    params:
      file: om-installation/installation.zip

- name: bbr-backup-pks-foundation
  plan:
  - aggregate:
    - get: bbr-release
      trigger: true
    - get: bbr-pipeline-tasks-repo
      trigger: true
  - task: lock-pks
    file: bbr-pipeline-tasks-repo/tasks/lock-pks/task.yml
    params:
      <<: *opsman_credentials
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
  - aggregate:
    - task: bbr-backup-director
      privileged: true
      file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.yml
      params:
        <<: *opsman_credentials
      on_failure:
        task: bbr-cleanup-director
        file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-director/task.yml
        params:
          <<: *opsman_credentials
    - task: bbr-backup-pks
      file: bbr-pipeline-tasks-repo/tasks/bbr-backup-pks/task.yml
      params:
        <<: *opsman_credentials
      on_failure:
        task: bbr-cleanup-pks
        file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pks/task.yml
        params:
          <<: *opsman_credentials
    - task: bbr-backup-pks-clusters
      file: bbr-pipeline-tasks-repo/tasks/bbr-backup-pks-clusters/task.yml
      params:
        <<: *opsman_credentials
      on_failure:
        task: bbr-cleanup-pks-clusters
        file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pks-clusters/task.yml
        params:
          <<: *opsman_credentials
  - aggregate:
    - put: director-backup-bucket
      params:
        file: director-backup-artifact/director-backup.tar
    - put: pks-backup-bucket
      params:
        file: pks-backup-artifact/pks-backup.tar
    - put: pks-backup-bucket
      params:
        file: pks-clusters-backup-artifact/pks-clusters-backup.tar
  ensure:
    task: unlock-pks
    file: bbr-pipeline-tasks-repo/tasks/unlock-pks/task.yml
    params:
      <<: *opsman_credentials

- name: validate-sample-pipeline-prs
  plan:
  - aggregate:
    - get: bbr-pipeline-tasks-repo
      trigger: true
      resource: bbr-pipeline-tasks-prs
    - get: backup-and-restore-ci
  - put: bbr-pipeline-tasks-prs
    params:
      context: validation-of-sample-pks-pipeline
      path: bbr-pipeline-tasks-repo
      status: pending
  - task: validate-pipeline
    file: backup-and-restore-ci/tasks/validate-pipeline/task.yml
    input_mapping:
      pipeline: bbr-pipeline-tasks-repo
    params:
      PIPELINE_PATH: examples/pks-pipeline.yml
      SECRETS_PATH: examples/pks-secrets.yml
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: validation-of-sample-pks-pipeline
        path: bbr-pipeline-tasks-prs
        status: failure
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: validation-of-sample-pks-pipeline
        path: bbr-pipeline-tasks-prs
        status: success

- name: bbr-backup-pks-foundation-prs
  plan:
  - aggregate:
    - get: bbr-release
    - get: bbr-pipeline-tasks-repo
      trigger: true
      resource: bbr-pipeline-tasks-prs
  - aggregate:
    - put: bbr-pipeline-tasks-prs
      params:
        context: lock-pks
        path: bbr-pipeline-tasks-repo
        status: pending
    - put: bbr-pipeline-tasks-prs
      params:
        context: bbr-backup-pks
        path: bbr-pipeline-tasks-repo
        status: pending
    - put: bbr-pipeline-tasks-prs
      params:
        context: bbr-cleanup-pks
        path: bbr-pipeline-tasks-repo
        status: pending
    - put: bbr-pipeline-tasks-prs
      params:
        context: bbr-backup-pks-clusters
        path: bbr-pipeline-tasks-repo
        status: pending
    - put: bbr-pipeline-tasks-prs
      params:
        context: bbr-cleanup-pks-clusters
        path: bbr-pipeline-tasks-repo
        status: pending
    - put: bbr-pipeline-tasks-prs
      params:
        context: unlock-pks
        path: bbr-pipeline-tasks-repo
        status: pending
  - task: lock-pks
    file: bbr-pipeline-tasks-repo/tasks/lock-pks/task.yml
    params:
      <<: *opsman_credentials
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: lock-pks
        path: bbr-pipeline-tasks-repo
        status: success
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: lock-pks
        path: bbr-pipeline-tasks-repo
        status: failure
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
  - aggregate:
    - task: bbr-backup-pks
      file: bbr-pipeline-tasks-repo/tasks/bbr-backup-pks/task.yml
      params:
        <<: *opsman_credentials
      on_failure:
        put: bbr-pipeline-tasks-prs
        params:
          context: bbr-backup-pks
          path: bbr-pipeline-tasks-repo
          status: failure
      ensure:
        task: bbr-cleanup-pks
        file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pks/task.yml
        params:
          <<: *opsman_credentials
        on_success:
          put: bbr-pipeline-tasks-prs
          params:
            context: bbr-cleanup-pks
            path: bbr-pipeline-tasks-repo
            status: success
        on_failure:
          put: bbr-pipeline-tasks-prs
          params:
            context: bbr-cleanup-pks
            path: bbr-pipeline-tasks-repo
            status: failure
    - task: bbr-backup-pks-clusters
      file: bbr-pipeline-tasks-repo/tasks/bbr-backup-pks-clusters/task.yml
      params:
        <<: *opsman_credentials
      on_failure:
        put: bbr-pipeline-tasks-prs
        params:
          context: bbr-backup-pks-clusters
          path: bbr-pipeline-tasks-repo
          status: failure
      ensure:
        task: bbr-cleanup-pks-clusters
        file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pks-clusters/task.yml
        params:
          <<: *opsman_credentials
        on_success:
          put: bbr-pipeline-tasks-prs
          params:
            context: bbr-cleanup-pks-clusters
            path: bbr-pipeline-tasks-repo
            status: success
        on_failure:
          put: bbr-pipeline-tasks-prs
          params:
            context: bbr-cleanup-pks-clusters
            path: bbr-pipeline-tasks-repo
            status: failure
  - aggregate:
    - put: pks-backup-bucket
      params:
        file: pks-backup-artifact/pks-backup.tar
      on_success:
        put: bbr-pipeline-tasks-prs
        params:
          context: bbr-backup-pks
          path: bbr-pipeline-tasks-repo
          status: success
      on_failure:
        put: bbr-pipeline-tasks-prs
        params:
          context: bbr-backup-pks
          path: bbr-pipeline-tasks-repo
          status: failure
    - put: pks-backup-bucket
      params:
        file: pks-clusters-backup-artifact/pks-clusters-backup.tar
      on_success:
        put: bbr-pipeline-tasks-prs
        params:
          context: bbr-backup-pks-clusters
          path: bbr-pipeline-tasks-repo
          status: success
      on_failure:
        put: bbr-pipeline-tasks-prs
        params:
          context: bbr-backup-pks-clusters
          path: bbr-pipeline-tasks-repo
          status: failure
  ensure:
    task: unlock-pks
    file: bbr-pipeline-tasks-repo/tasks/unlock-pks/task.yml
    params:
      <<: *opsman_credentials
    on_success:
      put: bbr-pipeline-tasks-prs
      params:
        context: unlock-pks
        path: bbr-pipeline-tasks-repo
        status: success
    on_failure:
      put: bbr-pipeline-tasks-prs
      params:
        context: unlock-pks
        path: bbr-pipeline-tasks-repo
        status: failure
