---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.11.0

inputs:
- name: backup-and-restore-ci
- name: bbl-state

params:
  NAME: # name for the config
  TYPE: # one of: cloud, runtime, cpi
  BBL_STATE_DIR: # path to bbl state dir in 'bbl-state' input
  CONFIG_PATH: # path to config to upload

run:
  path: backup-and-restore-ci/tasks/update-config/task.sh
