---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: terraform-state

outputs:
- name: terraform-state-updated

params:
  TERRAFORM_OPERATION: apply # Set terraform command to run; e.g. destroy or apply
  TERRAFORM_STATE_DIR: terraform-state
  TERRAFORM_STATE_PREPARE_CMD:  # Optional command to run before using terrform-state repository
  OUTPUT_TERRAFORM_STATE_DIR: terraform-state-updated
  ENVIRONMENT_NAME:
  GIT_USER_NAME:
  GIT_USER_EMAIL:

run:
  path: backup-and-restore-ci/tasks/terraform-operation/task.sh
