---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: bosh-backup-and-restore-meta

outputs:
- name: updated-meta

params:
  OPS_FILE_PATH:

run:
  path: backup-and-restore-ci/tasks/bbl-update-director-vm-type/task.sh
