---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: bosh-backup-and-restore-meta

params:
  BOSH_DEPLOYMENT:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

  BOSH_CA_CERT_DIR:
  BOSH_CA_CERT_PATH:
  BOSH_CA_CERT_PREPARE_CMD: # Optional command to run before using bosh ca cert repository
  TEAM_GPG_KEY:

run:
  path: backup-and-restore-ci/tasks/bosh-delete-deployment/task.sh
