---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: bosh-backup-and-restore-meta

params:
  BOSH_DEPLOYMENT:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT_DIR: bosh-backup-and-restore-meta
  BOSH_CA_CERT_PATH:

run:
  path: backup-and-restore-ci/tasks/bosh-delete-deployment/task.sh
