---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: bosh-backup-and-restore
- name: bosh-backup-and-restore-meta
- name: backup-and-restore-ci

params:
  JUMPBOX_HOST:
  JUMPBOX_USER:
  JUMPBOX_SSH_KEY:

  CREDHUB_SERVER:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_CA_CERT:
  BOSH_DEPLOYMENT:

  DIRECTOR_HOST:
  DIRECTOR_SSH_USERNAME:

run:
  path: backup-and-restore-ci/tasks/bbr-system-director/task.sh
