---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: s3-benchmark-binary
- name: app

params:
  CF_API:
  CF_ADMIN_PASSWORD:
  MYSQL_HOST:
  MYSQL_ROOT_PASSWORD:
  MYSQL_DATABASE:
  MYSQL_DATABASE_TABLE:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  DROPLETS_BUCKET:
  BUILDBPACKS_BUCKET:
  PACKAGES_BUCKET:
  RESOURCES_BUCKET:
  CF_ORG: test
  CF_SPACE: test
  NUMBER_OF_APPS: 100

run:
  path: backup-and-restore-ci/tasks/s3-benchmarking/task.sh
