# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: backup-and-restore-sdk-release
- name: bosh-backup-and-restore-meta

run:
  path: backup-and-restore-ci/tasks/postgres-system-tests/task.sh

params:
  TEAM_GPG_KEY:
  BOSH_CLIENT_SECRET:
  BOSH_CLIENT:
  POSTGRES_PASSWORD:
  POSTGRES_USERNAME:
  POSTGRES_SSL_USERNAME:
  POSTGRES_HOSTNAME:
  POSTGRES_PORT:
  POSTGRES_CA_CERT:
  POSTGRES_CLIENT_CERT:
  POSTGRES_CLIENT_KEY:
  SSH_PROXY_HOST:
  SSH_PROXY_USER:
  SSH_PROXY_PRIVATE_KEY:
  SDK_DEPLOYMENT: backup-restorer
  SDK_INSTANCE_GROUP: database-backup-restorer
  TEST_TLS_VERIFY_IDENTITY: true
  TEST_SSL_USER_REQUIRES_SSL: true
  TEST_SUITE_NAME:
