---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: terraform-state
- name: gcp-db-certs

outputs:
- name: gcp-db-certs

params:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: backup-and-restore-ci/tasks/create-gcp-db-certs/task.sh
