---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: repo

run:
  path: backup-and-restore-ci/tasks/check-for-changes/task.sh
