---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: terraform-state
- name: bosh-vars-store
- name: stemcell

outputs:
- name: b-drats-integration-config

params:
  OUTPUT_DIR: b-drats-integration-config
  BOSH_VARS_STORE_PATH:  # Path to bosh director vars-store YAML file
  BOSH_SSH_USERNAME: jumpbox
  TIMEOUT_IN_MINUTES: 30
  BOSH_CLIENT: admin
  INCLUDE_DEPLOYMENT_TESTCASE: true
  INCLUDE_CLEAN_UP_TESTCASE: true
  INCLUDE_TRUNCATE_DB_BLOBSTORE_TESTCASE: true
  STEMCELL_PATH:

run:
  path: backup-and-restore-ci/tasks/extract-b-drats-integration-config/task.sh
