---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-ci
- name: terraform-state
- name: bosh-vars-store

outputs:
- name: b-drats-integration-config

params:
  OUTPUT_DIR: b-drats-integration-config
  TERRAFORM_STATE_PREPARE_CMD:  # Optional command to run before using terraform-state repository
  TERRAFORM_STATE_PATH:  # Path to terraform.tfstate
  BOSH_VARS_STORE_PREPARE_CMD:  # Optional command to run before using bosh-state repository
  BOSH_VARS_STORE_PATH:  # Path to bosh director vars-store YAML file
  BOSH_SSH_USERNAME: jumpbox
  TIMEOUT_IN_MINUTES: 30
  BOSH_CLIENT: admin

run:
  path: backup-and-restore-ci/tasks/extract-b-drats-integration-config/task.sh
