---
platform: linux

image_resource:
  type: registry-image
  source: {repository: devtools-docker-local.artifactory.eng.vmware.com/vmware/nimbus/nimbus-worker}

inputs:
- name: backup-and-restore-ci

params:
  USER:
  WORKER_IDS:

run:
  path: backup-and-restore-ci/tasks/renew-nimbus-worker-vm/task.sh
