---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfplatformrecovery/backup-and-restore-minimal}

inputs:
- name: backup-and-restore-ci
- name: env-pool

run:
  path: backup-and-restore-ci/tasks/enable-br-on-toolsmiths-env/task.sh
