---
resources:
- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git

# - name: bosh-disaster-recovery-acceptance-tests-prs
#   type: pull-request
#   source:
#     repo: cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests
#     access_token: ((github-access-token))
#     branch: master

- name: bosh-disaster-recovery-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests.git
    branch: master

- name: bosh-backup-and-restore-meta
  type: git
  source:
    uri: git@github.com:pivotal-cf/bosh-backup-and-restore-meta.git
    private_key: ((git-private-key))
    branch: master

- name: backup-and-restore-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/backup-and-restore-ci.git
    private_key: ((git-private-key))
    branch: master

- name: bbr-binary-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github-access-token))

jobs:
- name: deploy-bosh-bengal-tiger
  serial: true
  serial_groups: [bengal-tiger]
  plan:
  - aggregate:
    - get: bosh-disaster-recovery-acceptance-tests
    - get: bosh-backup-and-restore-meta
    - get: backup-and-restore-ci
    - get: bosh-deployment
  - task: terraform-apply
    file: backup-and-restore-ci/tasks/terraform-apply/task.yml
    input_mapping:
      terraform-state: bosh-backup-and-restore-meta
    params:
      ENVIRONMENT_NAME: b-drats-bengal-tiger
      TERRAFORM_STATE_PREPARE_CMD: unlock-ci.sh
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      GIT_USER_NAME: "PCF Backup & Restore CI"
      GIT_USER_EMAIL: "cf-lazarus@pivotal.io"
    ensure:
      put: bosh-backup-and-restore-meta
      params:
        repository: meta-with-updated-terraform
        rebase: true
  - task: bosh-create-env
    file: backup-and-restore-ci/tasks/bosh-create-env/task.yml
    input_mapping:
      bosh-state: bosh-backup-and-restore-meta
    params:
      ENVIRONMENT_NAME: "b-drats-bengal-tiger"
      BOSH_STATE_PREPARE_CMD: unlock-ci.sh
      TEAM_GPG_KEY: ((team-gpg-key))  # Required by unlock-ci.sh
      OPS_FILES: "gcp/cpi.yml external-ip-not-recommended.yml jumpbox-user.yml"
      DIRECTOR_NAME: "bengal-tiger"
      PROJECT_ID: "cf-backup-and-restore"
      ZONE: "europe-west1-b"
      TAGS: "[bengal-tiger-director]"
      IP: ((bengal-tiger-director-ip))
      NETWORK: "bengal-tiger"
      SUBNET: "bengal-tiger-director"
    ensure:
      put: bosh-backup-and-restore-meta
      params:
        repository: meta-with-updated-bosh-state
        rebase: true


- name: run-b-drats-master
  serial: true
  serial_groups: [bengal-tiger]
  plan:
  - get: bosh-disaster-recovery-acceptance-tests
    passed: [deploy-bosh-bengal-tiger]
  - task: run-b-drats
    file: bosh-disaster-recovery-acceptance-tests/ci/bdrats/task.yml
