---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: backup-and-restore-ci

params:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: backup-and-restore-ci/tasks/delete-unattached-disks/task.sh
