---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore-minimal}

params:
  CF_API_URL:
  RETRY_COUNT: 5

run:
  path: sh
  args:
  - -exc
  - |
    curl ${CF_API_URL} --fail --retry ${RETRY_COUNT} --verbose --insecure