---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore-minimal}

inputs:
- name: backup-and-restore-ci

params:
  CF_API_URL:
  RETRY_COUNT: 5

run:
  path: backup-and-restore-ci/tasks/wait-for-cf-api/task.sh
