---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: pcfplatformrecovery/bbr-pcf-pipeline-tasks
    tag: final

inputs:
- name: backup-and-restore-ci
- name: pipeline

run:
  path: backup-and-restore-ci/tasks/validate-pipeline/task.sh

params:
  PIPELINE_PATH:
  SECRETS_PATH:
