---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundrylondon/bbr-pipeline
    tag: final

inputs:
- name: pipeline

run:
  path:

params:
  PIPELINE_PATH:
  SECRETS_PATH:
