---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: terraform-state
- name: bosh-vars-store
- name: backup-and-restore-ci

params:
  STEMCELL_URL:
  BOSH_VARS_STORE_PATH:  # Path to bosh director vars-store YAML file
  BOSH_CLIENT:

run:
  path: backup-and-restore-ci/tasks/upload-b-drats-stemcell/task.sh
