---
resources:
- name: docs-book-backup-and-restore
  type: git
  source:
    uri: git@github.com:pivotal-cf/docs-book-backup-and-restore.git
    private_key: ((git-private-key))
    branch: master
- name: docs-backup-and-restore
  type: git
  source:
    uri: git@github.com:pivotal-cf/docs-backup-and-restore.git
    private_key: ((git-private-key))
    branch: master
- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((pws-username))
    password: ((pws-password))
    organization: bbr
    space: docs
    # skip_cert_check: true

jobs:
- name: build-and-deploy-to-staging
  plan:
  - get: docs-book-backup-and-restore
    trigger: true
  - get: docs-backup-and-restore
    trigger: true
  - task: build
    file: docs-book-backup-and-restore/ci/build-and-deploy/task.yml
    params:
      GIT_SSH_KEY: ((git-private-key))
      APP_NAME: bbr-docs-staging
  - put: pws
    inputs:
    - name: docs-book-build
    params:
      path: docs-book-build/final_app
      manifest: docs-book-build/final_app/manifest.yml
- name: build-and-deploy-to-production
  plan:
  - get: docs-book-backup-and-restore
    passed: [build-and-deploy-to-staging]
  - get: docs-backup-and-restore
    passed: [build-and-deploy-to-staging]
  - task: build
    params:
      GIT_SSH_KEY: ((git-private-key))
      APP_NAME: bbr-docs-production
    file: docs-book-backup-and-restore/ci/build-and-deploy/task.yml
  - put: pws
    inputs:
    - name: docs-book-build
    params:
      path: docs-book-build/final_app
      manifest: docs-book-build/final_app/manifest.yml
